---
title: "Webscrape"
author: "Connor Greenhalgh"
date: "September 24, 2021"
output: pdf_document
---

Libraries I need
```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(xml2)
library(rjson)
```

THINGS TO DO
Get College/Last Played (international players)

Scrape NBA players
```{r}
url <- "https://www.basketball-reference.com/players/"
url2 <- "https://www.basketball-reference.com"
#player_dfs <- list()
nba_players_df <- data.frame()
nba_players_error <- data.frame()

tictoc::tic()
for(i in c(1:23,25:26)) {
  nba_player_list <- paste0(url, letters[i], "/") %>% 
    rvest::read_html()
  
  nba_player_df <-  nba_player_list %>%
    rvest::html_table()
  
  #player_dfs[[i]] <-  nba_player_df[[1]] 
  
  nba_player_href <-  nba_player_list %>% 
    rvest::html_nodes("th") %>%
    rvest::html_nodes("a") %>%
    rvest::html_attr("href")
  
  nba_recent_href <- nba_player_href[nba_player_df[[1]]$To >= 2016]
  
  nba_recent_name <- nba_player_df[[1]] %>%
    dplyr::filter(To >= 2016) %>%
    pull(Player)
  
  nba_recent_heights <- nba_player_df[[1]] %>%
    dplyr::filter(To >= 2016) %>%
    pull(Ht)
  
  nba_recent_weights <- nba_player_df[[1]] %>%
    dplyr::filter(To >= 2016) %>%
    pull(Wt)
  
  nba_recent_colleges <- nba_player_df[[1]] %>%
    dplyr::filter(To >= 2016) %>%
    pull(Colleges)
  
  for(j in 1:length(nba_recent_href)) {
    player_page <- try(paste0(url2, nba_recent_href[j], "/") %>% 
      rvest::read_html() %>% 
      rvest::html_nodes(xpath = '//comment()') %>%    # select comments
      rvest::html_text() %>%    # extract comment text
      paste(collapse = '') %>%    # collapse to single string
      rvest::read_html() %>% 
      rvest::html_nodes(xpath = '//*[@id="per_minute"]') %>% 
      rvest::html_table())
        
    player_table <- try(player_page[[1]] %>%
      slice(1:which(Season == "Career") - 1) %>%
      group_by(Season) %>% ## Players that were traded have multiple rows for same season. Just need the first one
      slice(1) %>%
      ungroup() %>%
      mutate(Player = nba_recent_name[j],
             Player_href = nba_recent_href[j],
             Weight = nba_recent_weights[j],
             Height = nba_recent_heights[j],
             # Birthdate = player_dfs[[1]]$`Birth Date`,
             College = nba_recent_colleges[j]))

    if (class(player_table)[1] == "try-error"){
      #### If no error there are 3 classes
      error_df <- data.frame("Player" = nba_recent_name[j],
                             "href" = nba_recent_href[j],
                             "i" = i,
                             "j" = j)
      nba_players_error <- rbind(nba_players_error, error_df)
    } else {
      
      if (any(names(player_table) != names(nba_players_df))) {
      names(player_table)[which(names(player_table) != names(nba_players_df))] <- names(nba_players_df)[which(names(player_table) != names(nba_players_df))]
      }
      nba_players_df <- rbind(nba_players_df, player_table)
    }
    # print(j)
  }
  # print(letters[i])
}
tictoc::toc()
beepr::beep()
```

Clean NBA players
```{r}
names(which(colSums(is.na(nba_players_df)) > 0))
nba_players_clean <- mutate_all(nba_players_df, ~replace(., is.na(.), 0)) %>% 
  filter(as.numeric(str_sub(nba_players_df$Season, -2)) %in% 17:21)
```

Scrape International Data
```{r}
url <- "https://www.basketball-reference.com/international/players/"
url2 <- "https://www.basketball-reference.com"
international_player_href <- list()
international_players_df <- data.frame()
empty_list <- list()
player_dfs <- list()
leagues <- c("Liga ACB", "LNB Pro A", "Lega Serie A", "Greek Basket League", "Israeli Super League", "Turkish Super League", "ABA Adriatic", "VTB United", "NBL Australia", "CBA China", "EuroLeague", "EuroCup")

tictoc::tic()
for(i in 1:26) {

  international_player_list <- paste0(url, letters[i], "/") %>% 
    rvest::read_html()
   
  players_href <- international_player_list %>%
    rvest::html_nodes(xpath='//*[@id="content"]/p/a[@href]') %>% 
    rvest::html_attr("href")
  
# }
  for(j in 1:length(players_href)) {
    
    #### DO I WANT TOURNAMENT DATA ####
    ##### Probably better way to do this but this was the simplest for me ####
    player_page <- try(paste0(url2, players_href[j], "/") %>% 
      rvest::read_html() %>% 
      rvest::html_nodes(xpath = '//*[@id="player-stats-per_minute-all-"]') %>% 
      rvest::html_table())
    
    if(length(player_page) == 0) {
      player_page <- try(paste0(url2, players_href[j], "/") %>% 
      rvest::read_html() %>% 
      rvest::html_nodes(xpath = '//*[@id="player-stats-per_minute-league-"]') %>% 
      rvest::html_table())
    }
    
    if(length(player_page) == 0) {
      player_page <- try(paste0(url2, players_href[j], "/") %>% 
      rvest::read_html() %>% 
      rvest::html_nodes(xpath = '//*[@id="player-stats-per_minute-league-_p"]') %>% 
      rvest::html_table())
    }
    
    # if(length(player_page) == 0) {
    #   player_page <- try(paste0(url2, players_href[j], "/") %>% 
    #   rvest::read_html() %>% 
    #   rvest::html_nodes(xpath = '//*[@id="player-stats-per_minute-tournament-"]') %>% 
    #   rvest::html_table())
    # }
    
    if(length(player_page) != 0 & class(player_page) != "try-error") {  
      player_df <- player_page[[1]]
      
      # Empty variable name which is a flag
      names(player_df)[which(names(player_df) == "")] <- "Flag"
      
      international_player_df <- player_df %>%
        filter(!grepl("Season", player_df$Season))
        # slice(1:which(contains("Season"))) %>%
        # group_by(Season) %>% ## Players that were traded have multiple rows for same season. Just need the first one
        # slice(1) %>%
        # ungroup()
      if(any(as.numeric(str_sub(international_player_df$Season, -2)) %in% 17:21)) {
        
        # height <- try(paste0(url2, players_href[j], "/") %>% 
        #                 rvest::read_html() %>% 
        #                 rvest::html_nodes(xpath = '//*[@id="meta"]/div/p[@href]'))
        # 
        # age <- try(paste0(url2, players_href[j], "/") %>% 
        #                 rvest::read_html() %>% 
        #                 rvest::html_nodes(xpath = '//*[@id="meta"]/div/p[3]/span[2]/nobr'))
        # 
        # college <- try(paste0(url2, players_href[j], '/') %>% 
        #                 rvest::read_html() %>% 
        #                 rvest::html_nodes(xpath = '//*[@id="meta"]/div/p[6]/a[2][@href')) %>% 
        #                 rvest::html_attr("href")
        
        temp <- international_player_df %>% 
          filter(as.numeric(str_sub(international_player_df$Season, -2)) %in% 17:21,
                 League %in% leagues) %>% 
          mutate(Player_href = players_href[j])
        
        international_players_df <- rbind(international_players_df, temp)
      }
    }
    # else{
    #   empty_list <- append(empty_list, paste0(letters[i],j))
    # }
    if(j %% 25 == 0) {print(j)}
  }
    print(letters[i])

    international_player_href <- append(international_player_href, players_href)
}  
tictoc::toc()

save(international_players_df, nba_players_clean, file = "players_dfs.Rdata")

```

Clean International Players
```{r}
international_players_clean <- international_players_df[-which(is.na(international_players_df$FG)),] %>% 
  mutate_all(~replace(., is.na(.), 0)) 

names(which(colSums(is.na(international_players_clean)) > 0))

names(international_players_df)[which(names(international_players_df) == "League")] <- "Lg"
names(international_players_df)[which(names(international_players_df) == "Team")] <- "Tm"
```

Save DataFrames
```{r}
save(nba_players_clean, international_players_clean, file = "basketball_players.Rdata")
```



